spring.application.name=api-gateway
server.port=8181

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

# Product Service Route
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=${PRODUCT_SERVICE_URL:http://product-service:8080}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product

# Order Service Route
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=${ORDER_SERVICE_URL:http://order-service:8080}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-boot-microservices-realm

# Tracing Properties
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Monitoring Properties (Actuator Prometheus + Health Endpoints)
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.enabled=true

management.zipkin.tracing.endpoint=http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
management.tracing.sampling.probability=1.0
