apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - app-config.yaml
  - infra.yaml
  - apps.yaml
  - ingress.yaml
  - network-policy.yaml
