apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  mysql-root-password: <YOUR_MYSQL_ROOT_PASSWORD>
  mysql-app-password: <YOUR_MYSQL_APP_PASSWORD>
  keycloak-db-password: <YOUR_KEYCLOAK_DB_PASSWORD>
  keycloak-admin-password: <YOUR_KEYCLOAK_ADMIN_PASSWORD>
